### ISSUE TITLE
推流画质问题

### ISSUE THREAD

**Issue by Denghongyuan** [lipku/LiveTalking#288]
推流的视频信息是profile Constrained Baseline, level 3.1, 4:2:0, 8-bit，清晰度非常低，我试过设置transceiver，但是推流时的profile还是baseline，是否有大佬能指教一二
`    for transceiver in pc.getTransceivers():
        if transceiver.kind == 'video':
            capabilities = RTCRtpSender.getCapabilities("video")
            preferences = [
                RTCRtpCodecCapability(
                    mimeType="video/H264",
                    clockRate=90000,
                    parameters={
                        "level-asymmetry-allowed": "1",
                        "packetization-mode": "1",
                        "profile-level-id": "42e01f"  # 对应baseline profile，high profile 应该是 42e01f
                    }
                )
            ]
            preferences += list(filter(lambda x: x.name == "VP8", capabilities.codecs))
            preferences += list(filter(lambda x: x.name == "rtx", capabilities.codecs))
            transceiver.setCodecPreferences(preferences)
            await transceiver.sender.send(RTCRtpSendParameters(
                    codecs=[RTCRtpCodecParameters(
                        mimeType="video/H264",
                        clockRate=90000,
                        payloadType=97,
                        parameters={
                            "level-asymmetry-allowed": "1",
                            "packetization-mode": "1",
                            "profile-level-id": "42e01f"  # 对应baseline profile，high profile 应该是 42e01f
                        }
                )]
            ))`

**Comment by Denghongyuan** [comment]
> 大佬, 你的问题解决了吗, 修改的什么配置

用av库解决了，因为VideoFrame是不带编码器属性的，所以会用推理的默认编码baseline，需要对VideoFrame重新编码，把编码后的第一个Packet对象推送到srs就行了，但是这会增加额外的cpu的负载，有更好的方法大家可以共同交流一下
`# 创建一个 H.264 编码器上下文
    codec = av.CodecContext.create('libx264', 'w')
    codec.options = {
        'profile': 'high',
        'preset': 'veryfast',  # 可以根据需要调整预设值
        'tune': 'zerolatency',  # 如果需要低延迟，可以设置为 'zerolatency'
        'loglevel': 'quiet',
    }
    codec.width = width
    codec.height = height
    codec.pix_fmt = 'yuv420p'
    codec.open()
    frame = VideoFrame.from_ndarray(image_frame, format="bgr24")
    packets = self.encoder.encode(frame)
    if not packets:
        raise ValueError("Failed to encode video frame")

    # 从列表中提取第一个 Packet 对象
    return packets[0]
`

**Comment by lswc225** [comment]
非常感谢. 大佬, 试了下你的方法, 会很卡. 并且推流质量也没有改善. 
我把这个代码前后的图片帧都保存了下, 发现质量基本没变, 可能我们的问题不是同一个.
`frame = VideoFrame.from_ndarray(image_frame, format="bgr24")
`

**Comment by Denghongyuan** [comment]
> 非常感谢. 大佬, 试了下你的方法, 会很卡. 并且推流质量也没有改善. 我把这个代码前后的图片帧都保存了下, 发现质量基本没变, 可能我们的问题不是同一个. `frame = VideoFrame.from_ndarray(image_frame, format="bgr24") `

你可以直接进入srs服务器查看视频流，可以查看到视频质量，如果H264/High就说明改成功了
![image](https://github.com/user-attachments/assets/e465a6c1-3e12-466a-97a8-a499aeefcccf)

**Comment by lswc225** [comment]
好的, 再次感谢, 我再试下.

**Comment by wz96cj** [comment]
求教 是在app.py文件下的async def run(push_url,sessionid) ### 方法下修改吗  能否提供下完整的修改代码

**Comment by Denghongyuan** [comment]
> 求教 是在app.py文件下的async def run(push_url,sessionid) ### 方法下修改吗 能否提供下完整的修改代码 参考另一个方法的这部分代码 好像不能生效 srs看不到对应的视频信息
> 
> ![Image](https://github.com/user-attachments/assets/ec44a85d-06e6-43fe-966c-eaee2f6eeff0)

这样设置无用的，我的理解是源帧如果没有经过处理，就是普通的清晰度，推流的源都是普通的清晰度了，自然无法设置更高的清晰度了
