### ISSUE TITLE
No module named '_raymarching_face'

### ISSUE THREAD

**Issue by ZyairYH** [lipku/LiveTalking#305]
## 环境
- win11
- conda python10
- cuda cuda12.4

## 报错内容
```
Traceback (most recent call last):
  File "D:\Workspace\LiveTalking\ernerf\raymarching\raymarching.py", line 10, in <module>
    import _raymarching_face as _backend
ModuleNotFoundError: No module named '_raymarching_face'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Workspace\LiveTalking\app.py", line 454, in <module>
    from ernerf.nerf_triplane.network import NeRFNetwork
  File "D:\Workspace\LiveTalking\ernerf\nerf_triplane\network.py", line 6, in <module>
    from .renderer import NeRFRenderer
  File "D:\Workspace\LiveTalking\ernerf\nerf_triplane\renderer.py", line 10, in <module>
    from .. import raymarching
  File "D:\Workspace\LiveTalking\ernerf\raymarching\__init__.py", line 1, in <module>
    from .raymarching import *
  File "D:\Workspace\LiveTalking\ernerf\raymarching\raymarching.py", line 12, in <module>
    from .backend import _backend
  File "D:\Workspace\LiveTalking\ernerf\raymarching\backend.py", line 31, in <module>
    _backend = load(name='_raymarching_face',
  File "D:\anaconda3\envs\nerfstream\lib\site-packages\torch\utils\cpp_extension.py", line 1202, in load
    return _jit_compile(
  File "D:\anaconda3\envs\nerfstream\lib\site-packages\torch\utils\cpp_extension.py", line 1425, in _jit_compile
    _write_ninja_file_and_build_library(
  File "D:\anaconda3\envs\nerfstream\lib\site-packages\torch\utils\cpp_extension.py", line 1537, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "D:\anaconda3\envs\nerfstream\lib\site-packages\torch\utils\cpp_extension.py", line 1785, in _run_ninja_build
    vc_env = distutils._msvccompiler._get_vc_env(plat_spec)
AttributeError: module 'distutils' has no attribute '_msvccompiler'. Did you mean: 'ccompiler'?
```

**Comment by AksaN1** [comment]
+1，请问解决了吗

**Comment by qiqi0308** [comment]
> ## 环境
> * win11
> * conda python10
> * cuda cuda12.4
> 
> ### 运行 python app.py 后报错 No module named '_raymarching_face' 如何解决
> ## 报错内容
> ```
> Traceback (most recent call last):
>   File "D:\Workspace\LiveTalking\ernerf\raymarching\raymarching.py", line 10, in <module>
>     import _raymarching_face as _backend
> ModuleNotFoundError: No module named '_raymarching_face'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\Workspace\LiveTalking\app.py", line 454, in <module>
>     from ernerf.nerf_triplane.network import NeRFNetwork
>   File "D:\Workspace\LiveTalking\ernerf\nerf_triplane\network.py", line 6, in <module>
>     from .renderer import NeRFRenderer
>   File "D:\Workspace\LiveTalking\ernerf\nerf_triplane\renderer.py", line 10, in <module>
>     from .. import raymarching
>   File "D:\Workspace\LiveTalking\ernerf\raymarching\__init__.py", line 1, in <module>
>     from .raymarching import *
>   File "D:\Workspace\LiveTalking\ernerf\raymarching\raymarching.py", line 12, in <module>
>     from .backend import _backend
>   File "D:\Workspace\LiveTalking\ernerf\raymarching\backend.py", line 31, in <module>
>     _backend = load(name='_raymarching_face',
>   File "D:\anaconda3\envs\nerfstream\lib\site-packages\torch\utils\cpp_extension.py", line 1202, in load
>     return _jit_compile(
>   File "D:\anaconda3\envs\nerfstream\lib\site-packages\torch\utils\cpp_extension.py", line 1425, in _jit_compile
>     _write_ninja_file_and_build_library(
>   File "D:\anaconda3\envs\nerfstream\lib\site-packages\torch\utils\cpp_extension.py", line 1537, in _write_ninja_file_and_build_library
>     _run_ninja_build(
>   File "D:\anaconda3\envs\nerfstream\lib\site-packages\torch\utils\cpp_extension.py", line 1785, in _run_ninja_build
>     vc_env = distutils._msvccompiler._get_vc_env(plat_spec)
> AttributeError: module 'distutils' has no attribute '_msvccompiler'. Did you mean: 'ccompiler'?
> ```

+1,蹲一个解决方法

**Comment by qiqi0308** [comment]
> ## 环境
> * win11
> * conda python10
> * cuda cuda12.4
> 
> ### 运行 python app.py 后报错 No module named '_raymarching_face' 如何解决
> ## 报错内容
> ```
> Traceback (most recent call last):
>   File "D:\Workspace\LiveTalking\ernerf\raymarching\raymarching.py", line 10, in <module>
>     import _raymarching_face as _backend
> ModuleNotFoundError: No module named '_raymarching_face'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\Workspace\LiveTalking\app.py", line 454, in <module>
>     from ernerf.nerf_triplane.network import NeRFNetwork
>   File "D:\Workspace\LiveTalking\ernerf\nerf_triplane\network.py", line 6, in <module>
>     from .renderer import NeRFRenderer
>   File "D:\Workspace\LiveTalking\ernerf\nerf_triplane\renderer.py", line 10, in <module>
>     from .. import raymarching
>   File "D:\Workspace\LiveTalking\ernerf\raymarching\__init__.py", line 1, in <module>
>     from .raymarching import *
>   File "D:\Workspace\LiveTalking\ernerf\raymarching\raymarching.py", line 12, in <module>
>     from .backend import _backend
>   File "D:\Workspace\LiveTalking\ernerf\raymarching\backend.py", line 31, in <module>
>     _backend = load(name='_raymarching_face',
>   File "D:\anaconda3\envs\nerfstream\lib\site-packages\torch\utils\cpp_extension.py", line 1202, in load
>     return _jit_compile(
>   File "D:\anaconda3\envs\nerfstream\lib\site-packages\torch\utils\cpp_extension.py", line 1425, in _jit_compile
>     _write_ninja_file_and_build_library(
>   File "D:\anaconda3\envs\nerfstream\lib\site-packages\torch\utils\cpp_extension.py", line 1537, in _write_ninja_file_and_build_library
>     _run_ninja_build(
>   File "D:\anaconda3\envs\nerfstream\lib\site-packages\torch\utils\cpp_extension.py", line 1785, in _run_ninja_build
>     vc_env = distutils._msvccompiler._get_vc_env(plat_spec)
> AttributeError: module 'distutils' has no attribute '_msvccompiler'. Did you mean: 'ccompiler'?
> ```

下面那个报错可以通过降级setuptools版本解决，降至72.1.0以下

**Comment by ZyairYH** [comment]
> _raymarching_face

https://github.com/lipku/LiveTalking/issues/119#issuecomment-2208184053

按照这个把里面4个子项目的重新构建一下

**Comment by qiqi0308** [comment]
> > _raymarching_face
> 
> [#119 (comment)](https://github.com/lipku/LiveTalking/issues/119#issuecomment-2208184053)
> 
> 按照这个把里面4个子项目的重新构建一下

[还是失败了
![1735455552258](https://github.com/user-attachments/assets/d5494772-df1e-4941-9c7a-2097f9958bb8)

**Comment by ZyairYH** [comment]
> > > _raymarching_face
> > 
> > 
> > [#119 (comment)](https://github.com/lipku/LiveTalking/issues/119#issuecomment-2208184053)
> > 按照这个把里面4个子项目的重新构建一下
> 
> [还是失败了 ![1735455552258](https://private-user-images.githubusercontent.com/162962703/399142615-d5494772-df1e-4941-9c7a-2097f9958bb8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2MTEyNDAsIm5iZiI6MTczNTYxMDk0MCwicGF0aCI6Ii8xNjI5NjI3MDMvMzk5MTQyNjE1LWQ1NDk0NzcyLWRmMWUtNDk0MS05YzdhLTIwOTdmOTk1OGJiOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMVQwMjA5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDVkZDNiOThhZDc3MDQxY2ZlYTAxYTFlMzkwZDEyZTY5NWQyNGNhNmYyZWY2YjA2ZGM5N2E2YzZiZDBmZmYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KrCUi0HRQe60RF4C5RxxvHMum9F4rzE0b2fYPsDJhrA)

Visual Studio 2019或者2022 你安装了吗

**Comment by qiqi0308** [comment]
> > > > _raymarching_face
> > > 
> > > 
> > > [#119 (comment)](https://github.com/lipku/LiveTalking/issues/119#issuecomment-2208184053)
> > > 按照这个把里面4个子项目的重新构建一下
> > 
> > 
> > [还是失败了 ![1735455552258](https://private-user-images.githubusercontent.com/162962703/399142615-d5494772-df1e-4941-9c7a-2097f9958bb8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2MTEyNDAsIm5iZiI6MTczNTYxMDk0MCwicGF0aCI6Ii8xNjI5NjI3MDMvMzk5MTQyNjE1LWQ1NDk0NzcyLWRmMWUtNDk0MS05YzdhLTIwOTdmOTk1OGJiOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMVQwMjA5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDVkZDNiOThhZDc3MDQxY2ZlYTAxYTFlMzkwZDEyZTY5NWQyNGNhNmYyZWY2YjA2ZGM5N2E2YzZiZDBmZmYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KrCUi0HRQe60RF4C5RxxvHMum9F4rzE0b2fYPsDJhrA)
> 
> Visual Studio 2019或者2022 你安装了吗

安装了！
![1735611199299](https://github.com/user-attachments/assets/8b3dd63b-5d32-4cfb-9a35-651905e8aeef)
