### ISSUE TITLE
torch  1.12.1加裁权重报错，是要升级torch版本吗

### ISSUE THREAD

**Issue by lijihua2017** [lipku/LiveTalking#323]
python app.py --model wav2lip --avatar_id wav2lip_avatar7 --max_session 4 --transport webrtc
Using cuda for inference.
Namespace(H=450, O=False, REF_FILE=None, REF_TEXT=None, TTS_SERVER='http://127.0.0.1:9880', W=450, amb_aud_loss=1, amb_dim=2, amb_eye_loss=1, asr=False, asr_model='cpierse/wav2vec2-large-xlsr-53-esperanto', asr_play=False, asr_save_feats=False, asr_wav='', att=2, au='data/au.csv', aud='', avatar_id='wav2lip_avatar7', batch_size=16, bbox_shift=5, bg_img='white', bound=1, ckpt='data/pretrained/ngp_kf.pth', color_space='srgb', cuda_ray=False, customopt=[], customvideo_config='', data_range=[0, -1], density_thresh=10, density_thresh_torso=0.01, dt_gamma=0.00390625, emb=False, exp_eye=False, fbg=False, finetune_lips=False, fix_eye=-1, fovy=21.24, fp16=False, fps=50, fullbody=False, fullbody_height=1080, fullbody_img='data/fullbody/img', fullbody_offset_x=0, fullbody_offset_y=0, fullbody_width=580, gui=False, head_ckpt='', ind_dim=4, ind_dim_torso=8, ind_num=10000, init_lips=False, l=10, lambda_amb=0.0001, listenport=8010, m=8, max_ray_batch=4096, max_session=4, max_spp=1, max_steps=16, min_near=0.05, model='wav2lip', num_rays=65536, num_steps=16, offset=[0, 0, 0], part=False, part2=False, patch_size=1, pose='data/data_kf.json', preload=0, push_url='http://localhost:1985/rtc/v1/whip/?app=live&stream=livestream', r=10, radius=3.35, scale=4, seed=0, smooth_eye=False, smooth_lips=False, smooth_path=False, smooth_path_window=7, torso=False, torso_imgs='', torso_shrink=0.8, train_camera=False, transport='webrtc', tts='edgetts', unc_loss=1, update_extra_interval=16, upsample_steps=0, warmup_step=10000, workspace='data/video')
Load checkpoint from: ./models/wav2lip.pth
Traceback (most recent call last):
  File "app.py", line 475, in <module>
    model = load_model("./models/wav2lip.pth")
  File "/root/metahuman-stream/lipreal.py", line 60, in load_model
    checkpoint = _load(path)
  File "/root/metahuman-stream/lipreal.py", line 51, in _load
    checkpoint = torch.load(checkpoint_path,weights_only=True)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
TypeError: 'weights_only' is an invalid keyword argument for load()

**Comment by lipku** [comment]
把weights_only参数去掉，版本不兼容

**Comment by lijihua2017** [comment]
> 把weights_only参数去掉，版本不兼容

需要升把torch升到高版本吗，推荐用1.12.1吗
