### ISSUE TITLE
人物嘴型模糊的问题

### ISSUE THREAD

**Issue by hour-note** [lipku/LiveTalking#331]
你好！在使用本项目的过程碰到人物嘴型模糊的问题，对此有以下几个疑问，望大佬能解答：

使用素材类型：1. 拍摄的素材；2. 可灵生成的视频素材；

问题描述：在使用拍摄的素材生成对口型视频的时候，基本不回出现嘴角模糊的情况，但使用可灵生成的视频素材进行视频推理（实时推理）的时候，会频繁出现嘴角模糊的情况

示例：
![image](https://github.com/user-attachments/assets/19b65cb7-2dfa-4645-9821-234305f28fbc)
![image](https://github.com/user-attachments/assets/99dfd22e-7204-4791-8168-84942fbb4ef2)

**Comment by lipku** [comment]
嘴角不要有胡须

**Comment by hour-note** [comment]
> 嘴角不要有胡须

谢谢解答，在使用musetalk实时推理的时候，出现嘴唇模糊的情况，请问这是什么情况？如何优化

原素材尺寸：512X512

示例：
https://github.com/user-attachments/assets/ac1a6c0c-296c-4891-98a9-ee507cb34a01

**Comment by lipku** [comment]
这个应该是模型的缺陷，没训练过这种数据。 你用离线推理看看

**Comment by hour-note** [comment]
> 这个应该是模型的缺陷，没训练过这种数据。 你用离线推理看看

谢谢解答！离线推理（视频）也会有这个问题，嘴唇和嘴角处会有模糊缺失的情况，这种情况是不是得自己训练musetalk模型了，喂数据。

**Comment by lipku** [comment]
是的

**Comment by hour-note** [comment]
> 是的

明白了，谢谢大佬解答！
