### ISSUE TITLE
使用rtmp可以推流但rtc不可以

### ISSUE THREAD

**Issue by yehx1** [lipku/LiveTalking#339]
使用
    parser.add_argument('--transport', type=str, default='rtcpush') #rtmp webrtc rtcpush
    parser.add_argument('--push_url', type=str, default='http://localhost:1985/rtc/v1/whip/?app=live&stream=livestream')
推流到SRS时一直没有图像。
换成rtmp与rtmp://localhost/live/livestream则可推流到SRS服务器，但是文字到视频输出延迟10秒左右，ffmpeg版本为5.1.2。

**Comment by LayKwokMing** [comment]
rtmp推流部分代码可以贴一下吗？为什么我看app.py没有rtmp推流的部分
