### ISSUE TITLE
正常运行，没有报错，但是视频不显示

### ISSUE THREAD

**Issue by cskkx1** [lipku/LiveTalking#342]
![image](https://github.com/user-attachments/assets/82295bf9-f564-4a5d-8ad6-2de35b5caf2d)
![image](https://github.com/user-attachments/assets/2fddf0cc-b2db-4fcd-9c3a-a9e30133109e)
![image](https://github.com/user-attachments/assets/13710107-68c8-4ae6-afab-fbc536bf5bbe)
以前运行的很正常，不知道为啥突然就不不行了

**Comment by cskkx1** [comment]
分析是没有推流到rtmp://10.89.1.237/live/livestream，这个如何解决

**Comment by cskkx1** [comment]
src控制台上的状态是有流的，但是就是拉不到流

**Comment by cskkx1** [comment]
公司网络管控，只给开了TCP权限，把UDP权限开了就可以了

**Comment by DBDXSS** [comment]
> 分析是没有推流到rtmp://10.89.1.237/live/livestream，这个如何解决

您好，请问您做了什么其他修改来推[rtmp](rtmp://10.89.1.237/live/livestream)了吗？
